resources:
  - name: jfrogtw_hw_repo
    type: GitRepo
    configuration:
      gitProvider: MyGitHub
      path: jfrogtw/jfrog-pipelines-hw
      branches:
        include: master
        
pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: jfrogtw_hw_repo
        execution:
          onExecute:
            - echo $MY_MESSAGE
           
